[system]
content = "You are an expert software analyst."

[user]
content = """
Here is the content of a file from a software project:

{content}

What APIs are used from the standard library? What APIs towards the operating 
system are used? Are these the modernized APIs or older ones that can or should 
be replaced with newer counterparts?
"""

